export const quizData = [
  // --- 第1ドメイン: 生成AIの基礎 (1-25) ---
  { id: 1, question: "複雑な数学的問題を解決する際、ステップバイステップで思考プロセスを出力させる手法は？", options: ["Few-shot", "Chain-of-Thought (CoT)", "Meta-prompting", "Directional-stimulus"], answer: "Chain-of-Thought (CoT)", explanation: "CoTは論理的飛躍を防ぐための標準的な手法です。" },
  { id: 2, question: "Amazon Bedrockで高スループット・低レイテンシ・低コストなモデルは？", options: ["Claude 3.5 Sonnet", "Claude 3 Haiku", "Llama 3 70B", "Mistral Large"], answer: "Claude 3 Haiku", explanation: "単純なタスクや速度重視の場面ではHaikuが最適です。" },
  { id: 3, question: "テキストを多次元のベクトル空間に変換するプロセスを何と呼びますか？", options: ["Tokenization", "Embedding", "Normalization", "Quantization"], answer: "Embedding", explanation: "意味的な類似性を計算可能にするための変換です。" },
  { id: 4, question: "画像の一部を編集し、文脈に合わせて新しい要素を追加する手法は？", options: ["Outpainting", "Inpainting", "Style Transfer", "Text-to-Image"], answer: "Inpainting", explanation: "画像の内側を書き換えるのがInpaintingです。" },
  { id: 5, question: "「unhappiness」を「un」「happi」「ness」と分ける手法は？", options: ["Word-level", "Character-level", "Subword-level", "Sentence-level"], answer: "Subword-level", explanation: "BPEやWordPieceなどのサブワード分割です。" },
  { id: 6, question: "回答生成前にソースから情報を検索しプロンプトに組み込む構成は？", options: ["Fine-tuning", "RLHF", "RAG", "Chain-of-Thought"], answer: "RAG", explanation: "検索拡張生成（Retrieval-Augmented Generation）です。" },
  { id: 7, question: "プロンプトインジェクションを防ぐためのAWSマネージドサービスは？", options: ["GuardDuty", "Bedrock Guardrails", "AWS WAF", "Inspector"], answer: "Bedrock Guardrails", explanation: "入力・出力の両方にフィルタを適用できます。" },
  { id: 8, question: "累積確率がしきい値に達するまでの候補から選択するパラメータは？", options: ["Temperature", "Top-K", "Top-P", "Stop sequences"], answer: "Top-P", explanation: "Nucleus Samplingとも呼ばれます。" },
  { id: 9, question: "最新のニュースをリアルタイムで回答させるための最良の方法は？", options: ["再学習", "長いコンテキスト", "Bedrock Agents", "Temperatureを最大にする"], answer: "Bedrock Agents", explanation: "外部ツール（検索API等）を呼び出せるエージェントが適しています。" },
  { id: 10, question: "基盤モデルの「知識のカットオフ」とは何を指しますか？", options: ["最大トークン数", "トレーニングデータの最終収集日", "コンテキストサイズ", "課金停止時間"], answer: "トレーニングデータの最終収集日", explanation: "それ以降の出来事についてはモデルは知識を持ちません。" },
  { id: 11, question: "マルチモーダルモデルの特徴は？", options: ["多言語対応", "テキスト、画像、音声等の多種データを処理", "多リージョン稼働", "多人数アクセス"], answer: "テキスト、画像、音声等の多種データを処理", explanation: "異なるモダリティを跨いで処理できるモデルです。" },
  { id: 12, question: "辞書にない単語（OOV）への一般的な対処法は？", options: ["削除", "サブワード分割または[UNK]", "エラー停止", "ランダム置換"], answer: "サブワード分割または[UNK]", explanation: "未知語を最小限に抑える仕組みです。" },
  { id: 13, question: "コンテキストウィンドウが200kトークンであることの意味は？", options: ["回答文字数", "入出力合計の処理可能上限", "1秒あたりのリクエスト数", "パラメータ数"], answer: "入出力合計の処理可能上限", explanation: "モデルが一度に「覚えておける」範囲です。" },
  { id: 14, question: "回答をJSON形式に固定したい場合に最も効果的なのは？", options: ["「JSONで答えて」と書く", "Few-shotとスキーマ明示", "Temperatureを0にする", "ストリーミング無効"], answer: "Few-shotとスキーマ明示", explanation: "具体例を示すのが最も確実です。" },
  { id: 15, question: "思考、行動、観察を繰り返すエージェントのループを何と呼びますか？", options: ["ReAct", "RLHF", "Backpropagation", "Gradient Descent"], answer: "ReAct", explanation: "Reasoning and Actingの略です。" },
  { id: 16, question: "拡散モデル（Diffusion Model）が画像を生成する仕組みは？", options: ["切り貼り", "ノイズからの除去", "ランダム配置", "テキスト直接変換"], answer: "ノイズからの除去", explanation: "逆拡散プロセスによって画像を構築します。" },
  { id: 17, question: "Titan Embeddings v2で次元数を増やすと一般的にどうなりますか？", options: ["精度向上の可能性があるがコスト増", "精度低下", "推論高速化", "無料になる"], answer: "精度向上の可能性があるがコスト増", explanation: "情報の解像度は上がりますがリソースも必要になります。" },
  { id: 18, question: "特定のフレーズを生成させない最も簡単な方法は？", options: ["フルファインチューニング", "Stop sequences", "VPCエンドポイント", "リージョン変更"], answer: "Stop sequences", explanation: "停止シーケンスで生成を強制終了させます。" },
  { id: 19, question: "「ステップバイステップで考えて」と付け加える手法はどれ？", options: ["Few-shot", "Zero-shot CoT", "Role prompting", "Self-consistency"], answer: "Zero-shot CoT", explanation: "例示なしで思考過程を促す手法です。" },
  { id: 20, question: "特定のタスクに特化させるため少量のラベル付きデータで調整することは？", options: ["Pre-training", "Fine-tuning", "Quantization", "Distillation"], answer: "Fine-tuning", explanation: "追加学習による微調整です。" },
  { id: 21, question: "アテンション・メカニズムの役割は？", options: ["メモリ節約", "各要素の重要度を動的に重み付け", "入力フィルタ", "パラメータをゼロにする"], answer: "各要素の重要度を動的に重み付け", explanation: "文脈の中の関連性に注目します。" },
  { id: 22, question: "モデルの「スループット」とは何を測定するものですか？", options: ["学習時間", "単位時間あたりの処理量", "ファイルサイズ", "DB容量"], answer: "単位時間あたりの処理量", explanation: "秒間のトークン数（TPS）などで表されます。" },
  { id: 23, question: "Temperatureを 0 に設定した場合の挙動は？", options: ["最もランダム", "決定論的（常に同じ回答）", "回答なし", "入力無視"], answer: "決定論的（常に同じ回答）", explanation: "確率最大のトークンのみが選ばれます。" },
  { id: 24, question: "LLMにおいてパラメータ数が多いことの一般的な意味は？", options: ["複雑な学習が可能だがリソースが必要", "正確性を保証", "無料", "オフライン動作"], answer: "複雑な学習が可能だがリソースが必要", explanation: "モデルの規模と性能（およびコスト）は比例傾向にあります。" },
  { id: 25, question: "画像生成における「ネガティブプロンプト」の用途は？", options: ["強調", "含めたくない要素の指定", "学習停止", "白黒化"], answer: "含めたくない要素の指定", explanation: "不要なものを排除するために使います。" },

  // --- 第2ドメイン: データ準備 (26-40) ---
  { id: 26, question: "RAG用にドキュメントを分割するプロセスを何と呼びますか？", options: ["Partitioning", "Chunking", "Sharding", "Indexing"], answer: "Chunking", explanation: "検索の最小単位を作る作業です。" },
  { id: 27, question: "チャンキングで「オーバーラップ」を設ける主な目的は何ですか？", options: ["冗長性向上", "文脈の喪失を防ぐ", "ストレージ節約", "検索高速化"], answer: "文脈の喪失を防ぐ", explanation: "境界線にある情報の断絶を防ぎます。" },
  { id: 28, question: "Bedrock Knowledge Basesでサポートされるサーバーレスベクトルエンジンは？", options: ["Aurora", "OpenSearch Serverless", "RDS", "DynamoDB"], answer: "OpenSearch Serverless", explanation: "マネージドなベクトルストアとして一般的です。" },
  { id: 29, question: "埋め込みベクトルの類似性計算で最も一般的な指標は？", options: ["L1 距離", "コサイン類似度", "ハミング距離", "ピアソン係数"], answer: "コサイン類似度", explanation: "ベクトルの向きの近さを測ります。" },
  { id: 30, question: "ベクトルサイズを変更しても精度を維持できる機能を何と呼びますか？", options: ["Scalable", "Matryoshka Embeddings", "Dynamic", "Sparse"], answer: "Matryoshka Embeddings", explanation: "Titan Embeddings v2の特徴的な機能です。" },
  { id: 31, question: "近似的な最近傍を高速に検索する手法を何と呼びますか？", options: ["Exact Match", "ANN", "Full Scan", "Binary Search"], answer: "ANN", explanation: "Approximate Nearest Neighborの略です。" },
  { id: 32, question: "RAGデータにメタデータを付与する利点は？", options: ["条件フィルタリングが可能になる", "次元削減", "暗号化不要", "Temperature制御"], answer: "条件フィルタリングが可能になる", explanation: "日付やカテゴリで検索範囲を絞れます。" },
  { id: 33, question: "日本語クエリで英語資料を検索したい場合に最も必要なものは？", options: ["翻訳Lambda", "多言語（Multilingual）埋め込みモデル", "別々のDB", "再学習"], answer: "多言語（Multilingual）埋め込みモデル", explanation: "異なる言語を同じベクトル空間に配置できます。" },
  { id: 34, question: "業界用語を正しくベクトル化できない場合の対策は？", options: ["ウィンドウ増", "用語集のコンテキスト追加や微調整", "チャンク巨大化", "大文字化"], answer: "用語集のコンテキスト追加や微調整", explanation: "モデルが知らない知識を補う必要があります。" },
  { id: 35, question: "OpenSearch Serverlessのインデックス作成で必要な設定は？", options: ["インスタンスタイプ", "次元数と類似度指標", "パラメータ数", "有効期限"], answer: "次元数と類似度指標", explanation: "ベクトルの仕様を合わせる必要があります。" },
  { id: 36, question: "S3に保存されたRAG用データを暗号化する最適な方法は？", options: ["パスワード付きZIP", "SSE-KMS", "Base64", "置換"], answer: "SSE-KMS", explanation: "AWSの標準的な暗号化手法です。" },
  { id: 37, question: "RAGにおける「ハイブリッド検索」とは何を指しますか？", options: ["複数LLM", "キーワード検索とベクトル検索の併用", "S3とDynamoDB", "CPUとGPU"], answer: "キーワード検索とベクトル検索の併用", explanation: "双方の弱点を補い合います。" },
  { id: 38, question: "Knowledge Basesの「取り込み」プロセスに含まれないのは？", options: ["Chunking", "埋め込み生成", "ベクトルストア保存", "フルファインチューニング"], answer: "フルファインチューニング", explanation: "取り込みは検索用データの準備までです。" },
  { id: 39, question: "「意味論的チャンキング」の主なメリットは？", options: ["低コスト", "トピックの区切りを考慮した分割が可能", "実装が簡単", "固定サイズ"], answer: "トピックの区切りを考慮した分割が可能", explanation: "文脈のまとまりを重視します。" },
  { id: 40, question: "ベクトルDBのインデックス再構築が必要なのはどの場合？", options: ["Temperature変更", "ソースデータ更新時", "ログイン時", "リージョン切り替え"], answer: "ソースデータ更新時", explanation: "最新のデータを反映させるために必要です。" },

  // --- 第3ドメイン: 生成AIアプリの開発 (41-82) ---
  { id: 41, question: "Bedrock Agentsが外部ツールを呼び出すために使用する設定は？", options: ["Knowledge Bases", "Action Groups", "Guardrails", "Routing"], answer: "Action Groups", explanation: "エージェントが「何ができるか」を定義します。" },
  { id: 42, question: "Lambdaと連携する際、レスポンス形式を記述する仕様書は？", options: ["OpenAPI (Swagger)", "XML", "Dockerfile", "IAM"], answer: "OpenAPI (Swagger)", explanation: "APIのインターフェース定義が必要です。" },
  { id: 43, question: "「InvokeModelWithResponseStream」を使用するメリットは？", options: ["安価", "逐次表示（UX向上）", "高精度", "暗号化強化"], answer: "逐次表示（UX向上）", explanation: "生成された順に文字を表示できます。" },
  { id: 44, question: "複数のモデルを単一のコード構造で呼び出せるBedrockの新APIは？", options: ["InvokeModel", "Converse API", "ApplyGuardrail", "ListModels"], answer: "Converse API", explanation: "抽象化された使いやすいAPIです。" },
  { id: 45, question: "回答の「根拠（引用元）」を提示したい場合、確認すべきフィールドは？", options: ["body", "citations", "status", "arn"], answer: "citations", explanation: "引用元情報が含まれるフィールドです。" },
  { id: 46, question: "メッセージ履歴を保存しコンテキストとして再送する機能は？", options: ["Chain", "Memory", "Agent", "Loader"], answer: "Memory", explanation: "LangChain等で使われる概念です。" },
  { id: 47, question: "エージェントの推論トレースをデバッグするための機能は？", options: ["Metrics", "Trace capability", "X-Ray", "CloudTrail"], answer: "Trace capability", explanation: "エージェントの思考過程を可視化します。" },
  { id: 48, question: "Provisioned Throughputが必要となる主なシナリオは？", options: ["テスト", "カスタムモデル使用やトラフィック保証", "S3読み込み", "パラメータ確認"], answer: "カスタムモデル使用やトラフィック保証", explanation: "専用の計算リソースを確保します。" },
  { id: 49, question: "APIキーをフロントエンドに持たせないためのベストプラクティスは？", options: ["JavaScript埋め込み", "API Gateway + Lambda + IAMロール", "S3公開", "直接呼び出し"], answer: "API Gateway + Lambda + IAMロール", explanation: "セキュアな仲介構成が必須です。" },
  { id: 50, question: "Retrieve APIで結果を得て、自作プロンプトで呼び出す構成は？", options: ["Fully Managed RAG", "Custom RAG", "Fine-tuning", "Compression"], answer: "Custom RAG", explanation: "柔軟なRAGの実装方法です。" },
  { id: 51, question: "Step Functionsを生成AIアプリで使用する主な利点は？", options: ["埋め込み作成", "複数ステップのワークフロー管理", "推論高速化", "S3作成"], answer: "複数ステップのワークフロー管理", explanation: "複雑な連鎖処理を制御できます。" },
  { id: 52, question: "不適切な入出力をフィルタリングするために構成すべき機能は？", options: ["VPC", "Bedrock Guardrails", "Shield", "Inspector"], answer: "Bedrock Guardrails", explanation: "コンテンツの安全性を担保します。" },
  { id: 53, question: "アクション実行前にユーザーに承認を求めるには？", options: ["タイムアウト延長", "Action GroupでConfirmation要求設定", "Temperature 0", "再作成"], answer: "Action GroupでConfirmation要求設定", explanation: "安全なツール実行のための機能です。" },
  { id: 54, question: "モデル評価で「ブランドの声」を評価する際に使えるワークフォースは？", options: ["Mechanical Turk", "AWS Managed Workforce", "Lambda", "EC2"], answer: "AWS Managed Workforce", explanation: "人間による主観評価が可能です。" },
  { id: 55, question: "特定のユーザーIDに関連するドキュメントのみを検索対象にするには？", options: ["1ファイル化", "メタデータフィルタリング適用", "DB作り直し", "プロンプトで頼む"], answer: "メタデータフィルタリング適用", explanation: "効率的な絞り込み手法です。" },
  { id: 56, question: "ThrottlingException（429）への最も適切な対応は？", options: ["無限リトライ", "指数バックオフとジッターを伴うリトライ", "リージョン変更", "電話"], answer: "指数バックオフとジッターを伴うリトライ", explanation: "AWS API呼び出しの基本原則です。" },
  { id: 57, question: "大規模なバッチ推論ジョブを非同期で実行するAPIは？", options: ["InvokeModel", "CreateModelInvocationJob", "RetrieveAndGenerate", "InvokeAgent"], answer: "CreateModelInvocationJob", explanation: "大量データ処理用の専用APIです。" },
  { id: 58, question: "ストリーミングレスポンスの配信形式を知るための技術概念は？", options: ["REST", "EventStream", "GraphQL", "SOAP"], answer: "EventStream", explanation: "逐次データを送るためのプロトコルです。" },
  { id: 59, question: "エージェントのバージョン管理に使用される仕組みは？", options: ["IAM", "エイリアスとバージョン", "S3名", "リージョン"], answer: "エイリアスとバージョン", explanation: "Lambdaと同様の管理手法です。" },
  { id: 60, question: "LangChainの「Chain」が果たす主な役割は？", options: ["保存", "コンポーネントの連結と実行", "帯域拡大", "トレーニング"], answer: "コンポーネントの連結と実行", explanation: "処理の連鎖を定義します。" },
  { id: 61, question: "Converse APIで会話の文脈を維持するために含めるべきは？", options: ["systemPrompt", "messages (対話履歴)", "stopSequences", "guardrailConfig"], answer: "messages (対話履歴)", explanation: "過去のやり取りを配列で渡します。" },
  { id: 62, question: "検索結果が長すぎて制限を超える場合の対策は？", options: ["削除", "Rerankingを行い上位のみ採用", "無視", "画像化"], answer: "Rerankingを行い上位のみ採用", explanation: "重要な情報だけを抽出します。" },
  { id: 63, question: "Agentsの指示（Instructions）に記述すべきでないものは？", options: ["役割", "タスクステップ", "DBパスワード", "トーン"], answer: "DBパスワード", explanation: "機密情報はシステム構成で管理すべきです。" },
  { id: 64, question: "モデルがツールを呼び出すべきか判断するプロセスは？", options: ["ランダム", "意図と定義済みツールの比較", "順番実行", "何もしない"], answer: "意図と定義済みツールの比較", explanation: "セマンティックな判断を行います。" },
  { id: 65, question: "引用元ドキュメントのS3パスを表示するために取得すべき場所は？", options: ["text", "retrievedReferences内のlocation", "S3検索", "パブリック化"], answer: "retrievedReferences内のlocation", explanation: "メタデータ内に場所が記録されています。" },
  { id: 66, question: "不確かな回答を避けるためのプロンプトの工夫は？", options: ["「何でも答えて」", "「答えがない場合は分からないと答えて」", "Temp 1.0", "短くする"], answer: "「答えがない場合は分からないと答えて」", explanation: "ハルシネーション抑制の基本です。" },
  { id: 67, question: "Lambdaアクションのタイムアウト設定で考慮すべき点は？", options: ["常に1秒", "モデル推論やAPI時間を考慮", "無視", "1時間"], answer: "モデル推論やAPI時間を考慮", explanation: "全体の処理時間を見積もる必要があります。" },
  { id: 68, question: "セッション情報をDynamoDBに保存する主な理由は？", options: ["画像保存", "会話履歴（状態）の永続化", "重み保存", "高速化"], answer: "会話履歴（状態）の永続化", explanation: "ステートレスな処理で状態を維持します。" },
  { id: 69, question: "Guardrailsの「PiiEntitiesConfig」は何を設定しますか？", options: ["IPアドレス", "PII（個人情報）の検知", "パラメータ", "DBサイズ"], answer: "PII（個人情報）の検知", explanation: "プライバシー保護のための設定です。" },
  { id: 70, question: "ReActにおける「Observation（観察）」とは何を指しますか？", options: ["考え", "外部ツールや検索の結果確認", "画面を見る", "停止"], answer: "外部ツールや検索の結果確認", explanation: "行動の結果を確認するステップです。" },
  { id: 71, question: "トークンカウントに最も影響を与えるのはどれですか？", options: ["バイト数", "モデル固有のトークナイザー", "パケット数", "クロック数"], answer: "モデル固有のトークナイザー", explanation: "モデルごとに分割ルールが異なります。" },
  { id: 72, question: "ツール使用（Tool use）機能を実装する際の定義に必要なのは？", options: ["ログイン情報", "名前、説明、引数のJSONスキーマ", "コード全体", "全実行ログ"], answer: "名前、説明、引数のJSONスキーマ", explanation: "モデルが「どう使うか」を知るための定義です。" },
  { id: 73, question: "質問を検索に適したクエリに変換させる手法は？", options: ["Query Rewriting", "Normalization", "Quantization", "Pruning"], answer: "Query Rewriting", explanation: "RAGの検索漏れを防ぐ高度な手法です。" },
  { id: 74, question: "カスタムモデルを削除せずに維持する際のコスト要因は？", options: ["ダウンロード料", "モデルのストレージ料金", "CPU使用料", "トークン料のみ"], answer: "モデルのストレージ料金", explanation: "モデルデータの保持にコストがかかります。" },
  { id: 75, question: "CSV形式で取得したい場合に最良な指示は？", options: ["「表にして」", "具体的にヘッダーを指定し例を示す", "「短く」", "何も書かない"], answer: "具体的にヘッダーを指定し例を示す", explanation: "構造を指定するのが最も正確です。" },
  { id: 76, question: "マルチリージョン構成の主なメリットは？", options: ["料金半分", "可用性とレジリエンスの向上", "パラメータ増", "簡単"], answer: "可用性とレジリエンスの向上", explanation: "障害時や制限時の回避策になります。" },
  { id: 77, question: "Knowledge Basesで「Hybrid Search」を有効にした場合の挙動は？", options: ["2LLM実行", "ベクトル検索とキーワード検索を並行し統合", "2DB必要", "2回暗号化"], answer: "ベクトル検索とキーワード検索を並行し統合", explanation: "検索の網羅性が高まります。" },
  { id: 78, question: "画像からテキストを抽出（OCR）するのに適したモデルは？", options: ["Titan Text", "Claude 3 (Vision機能付き)", "Llama 2", "Cohere"], answer: "Claude 3 (Vision機能付き)", explanation: "視覚理解が可能なモデルが必要です。" },
  { id: 79, question: "RetrieveAndGenerate APIでトーンをフォーマルに変更可能ですか？", options: ["不可", "プロンプトテンプレート指定で可能", "DB設定で可能", "再学習が必要"], answer: "プロンプトテンプレート指定で可能", explanation: "生成時の指示を上書きできます。" },
  { id: 80, question: "パラメータが不足している場合のAgentsの動作は？", options: ["エラー停止", "ユーザーに不足情報を尋ねる", "捏造", "無限ループ"], answer: "ユーザーに不足情報を尋ねる", explanation: "対話を通じて情報を補完しようとします。" },
  { id: 81, question: "Batch Inferenceの入力データ形式は？", options: [".exe", "JSONL", ".mp3", ".png"], answer: "JSONL", explanation: "1行1JSONの形式が標準です。" },
  { id: 82, question: "マーケットプレイスモデルを使用するためにまず必要なのは？", options: ["サーバー作成", "Model accessでの有効化リクエスト", "ダウンロード", "電話"], answer: "Model accessでの有効化リクエスト", explanation: "承諾（Accept）しないと使えません。" },

  // --- 第4ドメイン: モデルの評価と最適化 (83-123) ---
  { id: 83, question: "要約タスクで、正解との語彙の重なりを測定する指標は？", options: ["BLEU", "ROUGE", "Perplexity", "F1"], answer: "ROUGE", explanation: "要約の評価によく使われる指標です。" },
  { id: 84, question: "小さな行列を追加して効率的に学習させる手法は？", options: ["Full fine-tuning", "LoRA", "Pre-training", "DPO"], answer: "LoRA", explanation: "PEFTの代表的な手法です。" },
  { id: 85, question: "検索されたドキュメントが質問に答えるために適切かを評価する指標は？", options: ["Faithfulness", "Answer Relevance", "Context Precision", "Context Recall"], answer: "Context Precision", explanation: "検索の精度に関わる指標です。" },
  { id: 86, question: "回答が検索結果に基づいているか（ハルシネーション検知）を評価する指標は？", options: ["Faithfulness", "Answer Relevance", "Latency", "BLEU"], answer: "Faithfulness", explanation: "「忠実性」を測定します。" },
  { id: 87, question: "Bedrockのモデル評価で「自動」を選択した場合の挙動は？", options: ["ユーザー評価", "アルゴリズムによる指標計算", "自ら再学習", "SNS投稿"], answer: "アルゴリズムによる指標計算", explanation: "事前に定義された数値指標を出します。" },
  { id: 88, question: "データ型を変換してメモリ使用量を減らす技術は？", options: ["Distillation", "Quantization", "Pruning", "Sharding"], answer: "Quantization", explanation: "量子化による最適化です。" },
  { id: 89, question: "教師モデルの出力を生徒モデルに学習させる手法は？", options: ["Fine-tuning", "Knowledge Distillation", "RLHF", "Batch"], answer: "Knowledge Distillation", explanation: "「蒸留」と呼ばれます。" },
  { id: 90, question: "Provisioned Throughputを時間単位で購入する際の最小単位は？", options: ["1秒", "1分", "1時間（モデルユニット依存）", "1ヶ月"], answer: "1時間（モデルユニット依存）", explanation: "時間単位での予約となります。" },
  { id: 91, question: "言語モデルの「迷い」の度合いを示す指標は？", options: ["Perplexity", "Accuracy", "Recall", "Precision"], answer: "Perplexity", explanation: "数値が低いほど予測能力が高いことを示します。" },
  { id: 92, question: "検索結果を高性能モデルで再度ランク付けし直す手法は？", options: ["Pre-ranking", "Reranking", "Chunking", "Normalization"], answer: "Reranking", explanation: "最終的な検索精度を上げます。" },
  { id: 93, question: "SageMaker Clarifyを使用する主な目的は？", options: ["学習加速", "バイアス検出と説明可能性提供", "DBバックアップ", "VPCチェック"], answer: "バイアス検出と説明可能性提供", explanation: "AIの公平性を診断します。" },
  { id: 94, question: "LoRAの「ランク」パラメータの説明として正しいのは？", options: ["高いほど表現力が上がるがメモリ増", "常に1", "高いほど推論高速化", "層数を表す"], answer: "高いほど表現力が上がるがメモリ増", explanation: "追加する行列の複雑さを決定します。" },
  { id: 95, question: "Bedrockでファインチューニングがサポートされているモデルは？", options: ["すべて", "Amazon Titan等の対応モデル", "自作のみ", "一切不可"], answer: "Amazon Titan等の対応モデル", explanation: "モデルにより対応可否が分かれています。" },
  { id: 96, question: "プロンプトのわずかな変化に対して回答が一貫する度合いは？", options: ["回答速度", "堅牢性（Robustness）", "耐久性", "安定性"], answer: "堅牢性（Robustness）", explanation: "入力の揺らぎに対する強さです。" },
  { id: 97, question: "モデル評価における「Ground Truth」とは何を指しますか？", options: ["重み", "人間が作成した「正解データ」", "DB名", "全データ"], answer: "人間が作成した「正解データ」", explanation: "比較対象となる正しい答えです。" },
  { id: 98, question: "RLHFにおいて人間が行う主な作業は？", options: ["コードを書く", "回答を比較しランク付けする", "物理管理", "削除"], answer: "回答を比較しランク付けする", explanation: "人間の好みを学習に反映させます。" },
  { id: 99, question: "Batch Inferenceのコスト以外のメリットは？", options: ["リアルタイム性向上", "リアルタイム推論のクォータを消費しない", "精度劇的向上", "遅延ゼロ"], answer: "リアルタイム推論のクォータを消費しない", explanation: "大規模処理を安定して行えます。" },
  { id: 100, question: "検索情報が質問に答えるために必要十分かを評価する指標は？", options: ["Precision / Recall", "ROUGE-L", "Token count", "Cost"], answer: "Precision / Recall", explanation: "RAG評価の基本統計指標です。" },
  { id: 101, question: "量子化で「FP16」から「INT8」に変換するとメモリ消費量は？", options: ["不変", "約半分", "2倍", "0"], answer: "約半分", explanation: "データ長が半分になるためです。" },
  { id: 102, question: "Trainium や Inferentia を使用する主な目的は？", options: ["自動プログラミング", "コストパフォーマンス向上", "容量増", "画像編集"], answer: "コストパフォーマンス向上", explanation: "AWS専用のAIアクセラレータです。" },
  { id: 103, question: "DPOがRLHFの代替として注目される理由は？", options: ["大型サーバー必要", "報酬モデル不要で実装がシンプル", "低精度", "無料"], answer: "報酬モデル不要で実装がシンプル", explanation: "直接的な好みの最適化手法です。" },
  { id: 104, question: "特定の文体（例：シェイクスピア風）を学習させるのに適した手法は？", options: ["高速化", "ファインチューニング", "削除", "リージョン変更"], answer: "ファインチューニング", explanation: "振る舞いのカスタマイズに有効です。" },
  { id: 105, question: "Provisioned Throughputを解除するとカスタムモデルはどうなりますか？", options: ["削除", "保存されるが使用不可（再割当てまで）", "一般公開", "ベースに戻る"], answer: "保存されるが使用不可（再割当てまで）", explanation: "モデルデータは消えません。" },
  { id: 106, question: "モデル評価における「毒性（Toxicity）」の定義は？", options: ["バグ", "有害な表現を含む度合い", "電力消費", "ウイルス"], answer: "有害な表現を含む度合い", explanation: "安全性評価の重要項目です。" },
  { id: 107, question: "Few-shotの例示数を増やすと一般的にどう変化しますか？", options: ["精度低下", "形式に従いやすくなるがコスト増", "高速化", "不変"], answer: "形式に従いやすくなるがコスト増", explanation: "コンテキストが長くなるためです。" },
  { id: 108, question: "埋め込みモデル自体を微調整するのが有効なのは？", options: ["一般用語", "独自のドメイン知識（専門用語多）", "低速ネットワーク", "アイコン変更"], answer: "独自のドメイン知識（専門用語多）", explanation: "ベクトル配置の最適化です。" },
  { id: 109, question: "「回答が長すぎる」苦情へのコストとUXを両立する対策は？", options: ["大きくする", "maxTokens制限やプロンプト指示", "ブロック", "増設"], answer: "maxTokens制限やプロンプト指示", explanation: "出力を制御するのが最も速いです。" },
  { id: 110, question: "LLM-as-a-judge手法のメリットは？", options: ["常に正確", "高速かつ低コストに人間と相関する評価が可能", "評価不要", "電源オフ"], answer: "高速かつ低コストに人間と相関する評価が可能", explanation: "スケーラビリティに優れます。" },
  { id: 111, question: "PEFTの目的は何ですか？", options: ["全更新", "ごく一部のパラメータのみ更新し知識維持", "大型化", "ランダム"], answer: "ごく一部のパラメータのみ更新し知識維持", explanation: "低コストな微調整です。" },
  { id: 112, question: "ファインチューニングジョブ失敗時にまず確認すべきは？", options: ["S3パス、フォーマット、IAM", "ネット速度", "電池", "通知設定"], answer: "S3パス、フォーマット、IAM", explanation: "設定ミスが最も多い原因です。" },
  { id: 113, question: "セマンティック検索の弱点は？", options: ["類似検索不可", "「完全一致」が必要な検索で精度低下", "速すぎ", "誰でも使える"], answer: "「完全一致」が必要な検索で精度低下", explanation: "型番などの検索には不向きです。" },
  { id: 114, question: "METEORがBLEUより優れている点は？", options: ["高速", "語形変化や類義語を考慮できる", "名前", "全モデル"], answer: "語形変化や類義語を考慮できる", explanation: "より柔軟な言語評価です。" },
  { id: 115, question: "RAGにおいて「Reciprocal Rank Fusion (RRF)」は何に使われますか？", options: ["圧縮", "異なる検索結果の統合ランキング決定", "暗号化", "並列読み込み"], answer: "異なる検索結果の統合ランキング決定", explanation: "ハイブリッド検索で使われます。" },
  { id: 116, question: "「繰り返し問題」を改善するために調整すべきパラメータは？", options: ["Temp 0", "Presence / Frequency penalty", "ストリーミングオフ", "トークン削減"], answer: "Presence / Frequency penalty", explanation: "同じ単語の出現を抑制します。" },
  { id: 117, question: "Bedrockの「継続的な事前学習」の用途は？", options: ["個別回答", "ドメイン固有のラベルなしテキスト学習", "削除", "ロゴ"], answer: "ドメイン固有のラベルなしテキスト学習", explanation: "モデルの語彙と基礎知識を強化します。" },
  { id: 118, question: "推論コストに最も影響を与える要素は？", options: ["入出力トークン数", "明るさ", "所在地", "ブラウザ"], answer: "入出力トークン数", explanation: "従量課金の基本単位です。" },
  { id: 119, question: "Few-shotの例示を選ぶ際、最も効果的なのは？", options: ["無関係ジャンル", "多様性があり実タスクに近い例", "簡単のみ", "最長のみ"], answer: "多様性があり実タスクに近い例", explanation: "質が回答に直結します。" },
  { id: 120, question: "モデル評価結果を可視化するために統合できるサービスは？", options: ["QuickSight", "Glue", "IoT", "WorkMail"], answer: "QuickSight", explanation: "データ分析ツールです。" },
  { id: 121, question: "量子化によって引き起こされる主なデメリットは？", options: ["低速化", "僅かな推論精度の低下", "コスト増", "物理破壊"], answer: "僅かな推論精度の低下", explanation: "情報の劣化が避けられません。" },
  { id: 122, question: "ユーザーのクエリを拡張して複数の類似クエリを生成する手法は？", options: ["Query Expansion", "Index Pruning", "Masking", "Sharding"], answer: "Query Expansion", explanation: "検索ヒット率を高めます。" },
  { id: 123, question: "ガバナンスにおいて「説明可能性」が必要な理由は？", options: ["楽しみ", "根拠やプロセスを透明にするため", "難化", "料金下げ"], answer: "根拠やプロセスを透明にするため", explanation: "信頼性のために必要です。" },

  // --- 第5ドメイン: セキュリティとガバナンス (124-150) ---
  { id: 124, question: "顧客データがモデル学習に使用されることはありますか？", options: ["はい", "いいえ", "オプトアウト必要", "公開される"], answer: "いいえ", explanation: "Bedrockの大きなセキュリティ上の利点です。" },
  { id: 125, question: "Bedrockへの通信をプライベートネットワーク内に閉じる構成要素は？", options: ["IGW", "Interface VPC Endpoint (PrivateLink)", "Public S3", "SSH"], answer: "Interface VPC Endpoint (PrivateLink)", explanation: "インターネットを通さない接続です。" },
  { id: 126, question: "特定のモデルのみ使用を許可する制御方法は？", options: ["全員管理者", "IAMポリシーのResourceでモデルARN指定", "パスワード", "遮断"], answer: "IAMポリシーのResourceでモデルARN指定", explanation: "きめ細かなアクセス制御です。" },
  { id: 127, question: "GuardrailsでPIIを自動的に検出してマスクする機能は？", options: ["Content filters", "Sensitive information filters (PII)", "Denied topics", "Word filters"], answer: "Sensitive information filters (PII)", explanation: "個人情報保護機能です。" },
  { id: 128, question: "誰が何を尋ねたかのログ（入出力全文）を保存する機能は？", options: ["CloudTrail", "Model Invocation Logging", "Inspector", "Artifact"], answer: "Model Invocation Logging", explanation: "監査用のログです。" },
  { id: 129, question: "「責任あるAI」の5つの柱に含まれないものは？", options: ["公平性", "透明性", "堅牢性", "最大の利益"], answer: "最大の利益", explanation: "利益よりも倫理が優先されます。" },
  { id: 130, question: "KMSを使用して暗号化できる対象はどれですか？", options: ["ベースモデル重み", "カスタムモデル重み、KBインデックス、ログ等", "全データ", "請求書"], answer: "カスタムモデル重み、KBインデックス、ログ等", explanation: "顧客が作成したアセットが対象です。" },
  { id: 131, question: "システムプロンプトと入力を区切る記号を何と呼びますか？", options: ["Token", "Delimiter (デリミタ)", "Stop", "Mask"], answer: "Delimiter (デリミタ)", explanation: "インジェクション対策の一つです。" },
  { id: 132, question: "Guardrailsがブロックしたイベントのログはどこで確認できますか？", options: ["S3 / CloudWatch Logs", "Trusted Advisor", "ベルマーク", "IAM"], answer: "S3 / CloudWatch Logs", explanation: "ログ出力先を指定できます。" },
  { id: 133, question: "AI生成画像であることを識別可能にする技術は何と呼ばれますか？", options: ["Encryption", "Digital Watermarking", "Steganography", "Image Masking"], answer: "Digital Watermarking", explanation: "電子透かしです。" },
  { id: 134, question: "特定のリージョン内でのみデータを処理するように設定する重要性は？", options: ["不要", "法的・規制上の要件を満たすため重要", "コスト増のため避ける", "AWSが決定する"], answer: "法的・規制上の要件を満たすため重要", explanation: "データ主権の確保です。" },
  { id: 135, question: "有害でない短い会話を過剰にブロックしないための設定は？", options: ["最大しきい値", "しきい値のテストと評価による調整", "全ブロック", "なし"], answer: "しきい値のテストと評価による調整", explanation: "バランスが重要です。" },
  { id: 136, question: "モデルアクセスを管理できるのは誰ですか？", options: ["全員", "適切なIAM権限を持つ管理者", "プロバイダー", "ハッカー"], answer: "適切なIAM権限を持つ管理者", explanation: "権限管理の基本です。" },
  { id: 137, question: "CloudTrailで記録されるイベントには何が含まれますか？", options: ["プロンプト全文", "APIの実行履歴（誰が、いつ等）", "回答全文", "パラメータ"], answer: "APIの実行履歴（誰が、いつ等）", explanation: "管理プレーンのログです。" },
  { id: 138, question: "不当な偏りがある回答を防ぐ取り組みを何と呼びますか？", options: ["Bias mitigation", "Overfitting", "Underfitting", "Backpropagation"], answer: "Bias mitigation", explanation: "バイアス軽減です。" },
  { id: 139, question: "Guardrailsを複数のアプリで共通して使いたい場合、どうすればよいですか？", options: ["再作成", "GuardrailのIDをAPIパラメータに指定", "統合", "1リージョン化"], answer: "Guardrail의 IDをAPIパラメータに指定", explanation: "再利用可能な設計です。" },
  { id: 140, question: "特定の競合他社について話すのを禁止する設定項目は？", options: ["Content filters", "Denied topics", "PII filters", "Contextual"], answer: "Denied topics", explanation: "禁止トピックの設定です。" },
  { id: 141, question: "ドキュメントが無関係な場合に答えさせないようにする機能は？", options: ["PII Masking", "Contextual Grounding Check", "Denied Topics", "Token Limit"], answer: "Contextual Grounding Check", explanation: "根拠に基づくかチェックします。" },
  { id: 142, question: "責任共有モデルに基づき、ユーザーが責任を負うのはどの部分ですか？", options: ["モデルセキュリティ", "物理保護", "コード、データ、プロンプト、IAM", "学習アルゴリズム"], answer: "コード、データ、プロンプト、IAM", explanation: "クラウド上の設定はユーザーの責任です。" },
  { id: 143, question: "医療等の規制遵守のために確認すべきドキュメントは？", options: ["AWS Artifact (コンプライアンスレポート)", "ニュース", "Wikipedia", "SNS"], answer: "AWS Artifact (コンプライアンスレポート)", explanation: "公式の証明書ポータルです。" },
  { id: 144, question: "Lambdaの不正実行リスクへの対策はどれですか？", options: ["入力パラメータのバリデーション", "削除", "指示を短縮", "Temp 0"], answer: "入力パラメータのバリデーション", explanation: "コードレベルでの保護が必要です。" },
  { id: 145, question: "「全データ」をログに含める設定にした場合の懸念点は？", options: ["綺麗になる", "容量増と機密情報保護の重要性向上", "見えなくなる", "なし"], answer: "容量増と機密情報保護の重要性向上", explanation: "コストとセキュリティの両面でリスクがあります。" },
  { id: 146, question: "人間が回答を検証し、フィードバックを行うプロセスを何と呼びますか？", options: ["Human-in-the-loop (HITL)", "Auto-correction", "Self-healing", "Over-the-air"], answer: "Human-in-the-loop (HITL)", explanation: "人間介在型プロセスです。" },
  { id: 147, question: "特定の不適切な単語リストをブロックする機能は？", options: ["Word filters", "Sensitive filters", "Denied topics", "Content filters"], answer: "Word filters", explanation: "単語ベースのフィルタリングです。" },
  { id: 148, question: "S3へのアクセス権限をBedrockに与えるために必要なものは？", options: ["パブリック化", "適切な信頼関係を持つIAMロール", "root使用", "名前固定"], answer: "適切な信頼関係を持つIAMロール", explanation: "最小権限のIAMロールが必要です。" },
  { id: 149, question: "Resource: \"*\" を避けるべきなのはなぜですか？", options: ["停止するから", "最小権限の原則に従うため", "料金増", "AWS推奨"], answer: "最小権限の原則に従うため", explanation: "セキュリティの鉄則です。" },
  { id: 150, question: "継続的なモニタリングにおいて、監視すべきでない対象はどれですか？", options: ["エラー率", "不適切報告", "開発者のタイピング速度", "ブロック率"], answer: "開発者のタイピング速度", explanation: "システムの健全性とは無関係です。" }
];